/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Type = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const HelpRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : Type,
  'citizenMobile' : IDL.Text,
  'citizenPrincipal' : IDL.Principal,
  'citizenName' : IDL.Text,
  'timestamp' : IDL.Int,
  'assignedOfficer' : IDL.Opt(IDL.Principal),
  'location' : Location,
});
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptHelpRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeHelpRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getRequestsByStatus' : IDL.Func([Type], [IDL.Vec(HelpRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'sendSosRequest' : IDL.Func([Location], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Type = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const HelpRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : Type,
    'citizenMobile' : IDL.Text,
    'citizenPrincipal' : IDL.Principal,
    'citizenName' : IDL.Text,
    'timestamp' : IDL.Int,
    'assignedOfficer' : IDL.Opt(IDL.Principal),
    'location' : Location,
  });
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptHelpRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeHelpRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getRequestsByStatus' : IDL.Func([Type], [IDL.Vec(HelpRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'sendSosRequest' : IDL.Func([Location], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };