/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface HelpRequest {
  'id' : bigint,
  'status' : Type,
  'citizenMobile' : string,
  'citizenPrincipal' : Principal,
  'citizenName' : string,
  'timestamp' : bigint,
  'assignedOfficer' : [] | [Principal],
  'location' : Location,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export type Type = { 'resolved' : null } |
  { 'pending' : null } |
  { 'accepted' : null };
export interface UserProfile {
  'userType' : string,
  'name' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptHelpRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeHelpRequest' : ActorMethod<[bigint], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllRequests' : ActorMethod<[], Array<HelpRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getRequestsByStatus' : ActorMethod<[Type], Array<HelpRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string, string], undefined>,
  'sendSosRequest' : ActorMethod<[Location], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];